#!/bin/bash
# 删除旧文件
rm -f Makefile

# 使用 printf 确保制表符
{
echo 'TARGET = server'
echo 'OBJS = main.o timer/lst_timer.o http/http_conn.o log/log.o CGImysql/sql_connection_pool.o webserver.o config.o pool/http_conn_pool.o'
echo ''
echo 'CC = g++'
echo 'CFLAGS = -g -Wall'
echo ''
echo 'all: $(TARGET)'
echo ''
echo '$(TARGET): $(OBJS)'
printf '\t$(CC) $(CFLAGS) $(OBJS) -o $(TARGET) -lpthread -lmysqlclient\n'
echo ''
echo 'main.o: main.cpp'
printf '\t$(CC) $(CFLAGS) -c main.cpp -o main.o\n'
echo ''
echo 'timer/lst_timer.o: timer/lst_timer.cpp'
printf '\t$(CC) $(CFLAGS) -c timer/lst_timer.cpp -o timer/lst_timer.o\n'
echo ''
echo 'http/http_conn.o: http/http_conn.cpp'
printf '\t$(CC) $(CFLAGS) -c http/http_conn.cpp -o http/http_conn.o\n'
echo ''
echo 'log/log.o: log/log.cpp'
printf '\t$(CC) $(CFLAGS) -c log/log.cpp -o log/log.o\n'
echo ''
echo 'CGImysql/sql_connection_pool.o: CGImysql/sql_connection_pool.cpp'
printf '\t$(CC) $(CFLAGS) -c CGImysql/sql_connection_pool.cpp -o CGImysql/sql_connection_pool.o\n'
echo ''
echo 'webserver.o: webserver.cpp'
printf '\t$(CC) $(CFLAGS) -c webserver.cpp -o webserver.o\n'
echo ''
echo 'config.o: config.cpp'
printf '\t$(CC) $(CFLAGS) -c config.cpp -o config.o\n'
echo ''
echo 'pool/http_conn_pool.o: pool/http_conn_pool.cpp'
printf '\t$(CC) $(CFLAGS) -c pool/http_conn_pool.cpp -o pool/http_conn_pool.o\n'
echo ''
echo 'clean:'
printf '\trm -f $(OBJS) $(TARGET)\n'
echo ''
echo '.PHONY: all clean'
} > Makefile
